/*
 * Selling Partner API for Catalog Items
 * The Selling Partner API for Catalog Items provides programmatic access to information about items in the Amazon catalog.  For more information, refer to the [Catalog Items API Use Case Guide](doc:catalog-items-api-v2022-04-01-use-case-guide).
 *
 * OpenAPI spec version: 2022-04-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.myasinmanager.spapi.model.catalog;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A JSON object that contains structured item attribute data keyed by attribute
 * name. Catalog item attributes conform to the related product type definitions
 * available in the Selling Partner API for Product Type Definitions.
 */
@Data
public class ItemAttributes {

	private List<ItemListPrice> listPrice;


	@Data
	@AllArgsConstructor
	@NoArgsConstructor
	public class ItemListPrice {

		@SerializedName("currency")
		private String currency;
		
		@SerializedName("value")
		private Double value;
		
		@SerializedName("marketplaceId")
		private String marketplaceId;

	}


}
